In [118]:
import sklearn
import numpy as np

from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression
from sklearn.model_selection import train_test_split
mlp = MLPClassifier()

from environment.environment import Environment
from utils import save_pickle, load_pickle

In [96]:
env = Environment(brick_ip='ev3dev.local', get_state_mode='dict')
env.get_state()

{'bot': (155,),
 'cs': ((190, 162, 224),),
 'top': (96,),
 'ts1': (0,),
 'ts2': (0,)}

if on:
    calc_reward

In [108]:
class StateTrainer:
    def __init__(self, env, class_names, samples_per_class, clf, test_size=0.1):
        self.class_names = class_names
        self.class_map = {
            class_name: number for number, class_name in enumerate(self.class_names)
        }
        self.samples_per_class = samples_per_class
        self.clf = clf
        self.test_size = test_size
        
        self.env = env
        
        self.measurements = None
        self.X = None
        self.y = None
        
    def _rgb(self):
        return self.env.get_state()['cs'][0]
        
    def _button1_pressed(self):
        return self.env.get_state()['ts1'][0]
        
    def _gather_measurements(self):
        final_measurements = []
        for class_n, class_name in enumerate(self.class_names):
            class_measurements = []
            print(class_name)
            for i in range(self.samples_per_class):
                print("Press button 1 to collect a sample.")
                while not self._button1_pressed():
                    pass
                colors = self._rgb()
                class_measurements.append(colors)
                print("Collected sample:", colors, "of class", class_name)
            final_measurements.append(class_measurements)
        return final_measurements

    def get_data_for_training(self):
        if self.measurements is None:
            self.measurements = self._gather_measurements()
        else:
            print("Already have measurements.")
        
        X = np.concatenate(self.measurements)
        y_ = [[self.class_map[class_name]]*self.samples_per_class for class_name in self.class_names]
        y = np.concatenate(y_)
        self.X = X
        self.y = y
        
        return train_test_split(X, y, test_size=self.test_size, stratify=y)
    
    def train(self):
        X_train, X_test, y_train, y_test = self.get_data_for_training()
        self.clf.fit(X_train, y_train)
        return self.clf.score(X_test, y_test)
    
    def save_model(self, name):
        save_pickle(name, self.clf)

In [98]:
class_names = ['off', 'on']
samples_per_class = 20
st = StateTrainer(env, class_names, samples_per_class=samples_per_class, clf=mlp, test_size=0.1)
print(st.train())
st.save_model('mlp_on_off.pickle')

off
Press button 1 to collect a sample.
Collected sample: (192, 139, 144) of class off
Press button 1 to collect a sample.
Collected sample: (176, 95, 67) of class off
Press button 1 to collect a sample.
Collected sample: (186, 87, 67) of class off
Press button 1 to collect a sample.
Collected sample: (213, 87, 58) of class off
Press button 1 to collect a sample.
Collected sample: (182, 82, 82) of class off
Press button 1 to collect a sample.
Collected sample: (182, 108, 109) of class off
Press button 1 to collect a sample.
Collected sample: (176, 66, 69) of class off
Press button 1 to collect a sample.
Collected sample: (180, 60, 98) of class off
Press button 1 to collect a sample.
Collected sample: (197, 76, 79) of class off
Press button 1 to collect a sample.
Collected sample: (185, 62, 93) of class off
Press button 1 to collect a sample.
Collected sample: (180, 54, 75) of class off
Press button 1 to collect a sample.
Collected sample: (188, 74, 102) of class off
Press button 1 to c

In [99]:
mlp = load_pickle('on_or_off_classifier.pickle')

In [102]:
for i in range(5):
    while not button1_pressed():
        pass
    colors = st._rgb()
    print(mlp.predict(np.array(colors).reshape(1,-1)))

[1]
[1]
[1]
[1]
[1]


In [109]:
meas_save = st.measurements

In [125]:
class_names = ['white', 'black', 'dot']
samples_per_class = 20
st = StateTrainer(env, class_names, samples_per_class=samples_per_class, clf=LogisticRegressionCV(), test_size=0.1)
# st.measurements = meas_save
print(st.class_names, st.class_map)
print(st.train())
st.save_model('mlp_white_black.pickle')

['white', 'black', 'dot'] {'white': 0, 'black': 1, 'dot': 2}
white
Press button 1 to collect a sample.
Collected sample: (189, 178, 231) of class white
Press button 1 to collect a sample.
Collected sample: (182, 170, 222) of class white
Press button 1 to collect a sample.
Collected sample: (194, 183, 237) of class white
Press button 1 to collect a sample.
Collected sample: (190, 181, 233) of class white
Press button 1 to collect a sample.
Collected sample: (185, 176, 226) of class white
Press button 1 to collect a sample.
Collected sample: (203, 192, 245) of class white
Press button 1 to collect a sample.
Collected sample: (193, 182, 231) of class white
Press button 1 to collect a sample.
Collected sample: (190, 181, 233) of class white
Press button 1 to collect a sample.
Collected sample: (186, 178, 226) of class white
Press button 1 to collect a sample.
Collected sample: (190, 181, 234) of class white
Press button 1 to collect a sample.
Collected sample: (188, 179, 230) of class whit

C:\Users\Michal\AppData\Roaming\Python\Python36\site-packages\sklearn\linear_model\logistic.py:459: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Michal\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


1.0


In [126]:
clf = load_pickle('mlp_white_black.pickle')

In [128]:
for i in range(5):
    while not button1_pressed():
        pass
    colors = st._rgb()
    print(clf.predict_proba(np.array(colors).reshape(1,-1)))

[[5.56272072e-11 7.62900265e-01 2.37099735e-01]]
[[1.54198023e-13 7.44306985e-01 2.55693015e-01]]
[[2.17656940e-14 6.72710183e-01 3.27289817e-01]]
[[3.86693673e-11 7.32640336e-01 2.67359664e-01]]
[[9.24001487e-29 2.10605892e-01 7.89394108e-01]]
